services:
  - type: web
    name: cooking-game-frontend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: BACKEND_URL
        value: https://cooking-game-backend.onrender.com
    plan: free