services:
  - type: web
    name: cooking-game-backend
    env: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JAVA_OPTS
        value: "-Xmx512m -Xms256m"
    plan: free
    # Note: CORS is configured to allow requests from any origin
    # Health check will verify the application is running properly